

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'

- task: BatchScript@1
  inputs:
    filename: './power.bat'
    arguments: '3 4'

- task: BatchScript@1
  inputs:
    filename: './calc.bat'
    arguments: '100 200'